### ISSUE TITLE
Practice: Build a Grid - Icon Size in Step #5

### ISSUE THREAD

**Issue by lixoten** [google-developer-training/basic-android-kotlin-compose-training-courses#1]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-grid?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-grid#4

**In which task and step of the codelab can this issue be found?**
Step# 5

**Describe the problem**
Bit confusing, In provited github Solution the Icon size it is 12.dp but no mention in codelab that is should be.

**Steps to reproduce?**
1.  Look here https://github.com/google-developer-training/basic-android-kotlin-compose-training-courses/blob/main/app/src/main/java/com/example/courses/MainActivity.kt

**Additional information**
screenshots
![image](https://user-images.githubusercontent.com/52259786/201787181-12e19173-18c6-48e0-84ae-4d96f0f6d1a6.png)

**Comment by sc-gds-lxl** [comment]
Removed this dimension from the solution.
