### ISSUE TITLE
Build a Grid: Android Basics in Compose

### ISSUE THREAD

**Issue by gensart-ai** [google-developer-training/basic-android-kotlin-compose-training-courses#4]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-grid?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-grid#6

**In which task and step of the codelab can this issue be found?**
In Step 6 : Courses Grid

**Describe the problem**
I can't use `LazyVerticalGrid`, it says still unstable. Why i use `LazyVerticalGrid` because that seems would be match for the practice that on goes.

**Steps to reproduce?**
1. Add `LazyVerticalGrid` replacing `LazyColumn`.

**Versions**
_Android Studio version: 2021.3.1 Patch 1_ 
_API version of the emulator: Android 11 API Level 30_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sc-gds-lxl** [comment]
I cannot confirm without seeing your code, but `LazyVerticalGrid` is valid even as of the most recent compose versions and in the older versions seen in the solution code for this app. For reference, here is the import for `LazyVerticalGrid`:
`import androidx.compose.foundation.lazy.grid.LazyVerticalGrid` 
and the [source code](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/grid/LazyGridDsl.kt;l=64?q=LazyVerticalGrid)
