### ISSUE TITLE
Build a Grid: Android Basics in Compose

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-training-courses#5]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-grid?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-grid#5

https://developer.android.com/jetpack/compose/lists#lazy-grids

API Documentation problem:

@Composable
fun PhotoGrid(photos: List<Photo>) {
    LazyVerticalGrid(
        columns = GridCells.Adaptive(minSize = 128.dp)
    ) {
        items(photos) { photo ->
            PhotoItem(photo)
        }
    }
}

'columns' doesn't exist anymore, it's 'cells' now

**Comment by sc-gds-lxl** [comment]
`columns` is still a parameter for `LazyVerticalGrid`. It's usage can still be referenced in [`LazyGridDsl.kt'](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/grid/LazyGridDsl.kt;l=64?q=LazyVerticalGrid). This is still valid in current version of compose `1.4.0-beta02`. 

The solution code for this project still runs with the current version configuration and fully updated versions.
